### ISSUE TITLE
In-game issues regarding DJ

### ISSUE THREAD

**Issue by Sinisori** [paradoxum-games/bugs#18]
**Describe the bug** 

1. *DJ's range upgrades don't apply to the tower and only applies buffs in its original range*
https://streamable.com/h6ioho

**Expected behavior**
*DJ upgrades that give additional range towards DJ should work. In this scenario the projected range of the tower doesn't actually work and the buffs only work in the towers original range.*

2. *DJ's range buff does not apply to Commander's COA ability*
https://streamable.com/flr1a6

**Expected behavior**
*DJ should give Commander a boost in it's range which should also apply towards it's COA ability but doesn't. The range of the ability is not affected by DJ's range buff*

**Comment by SneakyWolfy** [comment]
Overlapping Issues from [Commander's Issue Thread](https://github.com/paradoxum-games/bugs/issues/16) that also affect DJ:
 - When 2 DJ are placed next to each other, towers will take priority over last upgraded instead of the highest level.
 - When 2 DJ are placed next to each other, towers will lose all DJ related buffs instead of defaulting to the next highest DJ buff in range.
