### ISSUE TITLE
[BUG] Cowboy doesn't give money after shooting 8 times

### ISSUE THREAD

**Issue by aeroartistryy** [paradoxum-games/bugs#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In cowboy's description, it says that it gives cash every 8th shot, but you don't gain any cash after it shoots 8 times (On level 0 and 1)

### Expected Behavior

You should be able to gain cash every 8th shot by cowboy.

### Steps To Reproduce

1. Join the lobby
2. Join a random map
3. Place down cowboy
4. Wait for cowboy to shoot 8 times

### Platforms Affected

- [X] Desktop
- [X] Tablet
- [X] Phone

### Additional Information

https://cdn.discordapp.com/attachments/970090804418867301/970534781941071872/2022-05-02_11-56-14.mp4

**Comment by SneakyWolfy** [comment]
This is backward; Cowboy is supposed to give cash every 5 shots (4 shots for golden cowboy). 

The reason why the description says once every 8 shots is because Cowboy used to have a 1/8 chance to give cash. This was changed for the current system and the description has yet to be updated.

Basically, the description is wrong, not the effect.

**Comment by Awes-3** [comment]
resolved in next release
